version: '3.8'

services:
  # Backend service with optimized development setup
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
      cache_from:
        - node:18-alpine
        - viny-backend-dev:latest
    image: viny-backend-dev:latest
    container_name: viny-backend-dev-opt
    ports:
      - "3001:3001"
    volumes:
      # Source code mounts for hot reload
      - ./server/src:/app/src:cached
      - ./server/prisma:/app/prisma:cached
      - ./server/package.json:/app/package.json:ro
      - ./server/tsconfig.json:/app/tsconfig.json:ro
      # Named volume for node_modules (better performance)
      - backend_node_modules:/app/node_modules
      # Persistent database
      - viny_db:/app/prisma
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=file:./viny.db
      - TSX_TSCONFIG_PATH=./tsconfig.json
    command: npm run dev
    networks:
      - viny-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # Frontend service with optimized build
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      cache_from:
        - node:18-alpine
        - viny-frontend-dev:latest
    image: viny-frontend-dev:latest
    container_name: viny-frontend-dev-opt
    ports:
      - "5173:5173"
    volumes:
      # Source code mounts for hot reload (cached for better performance)
      - ./src:/app/src:cached
      - ./public:/app/public:cached
      - ./index.html:/app/index.html:ro
      - ./vite.config.js:/app/vite.config.js:ro
      - ./package.json:/app/package.json:ro
      - ./tailwind.config.js:/app/tailwind.config.js:ro
      - ./postcss.config.js:/app/postcss.config.js:ro
      # Named volume for node_modules
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3001/api
      - VITE_HMR_HOST=localhost
    command: npm run dev -- --host 0.0.0.0 --port 5173
    networks:
      - viny-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  # Persistent volumes with optimized settings
  viny_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/db
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  viny-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: viny-br0