version: '3.8'

services:
  # Backend service
  backend:
    build: 
      context: ./server
      target: base
    container_name: viny-backend-dev
    ports:
      - "3001:3001"
    volumes:
      # Mount source code for hot reload
      - ./server/src:/app/src:ro
      - ./server/prisma:/app/prisma:ro
      - ./server/package.json:/app/package.json:ro
      - ./server/tsconfig.json:/app/tsconfig.json:ro
      # Mount node_modules as volume for performance
      - backend_node_modules:/app/node_modules
      # Persistent database
      - viny_db:/app/prisma
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=file:./viny.db
    command: npm run dev
    networks:
      - viny-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service  
  frontend:
    build:
      context: .
      target: build-deps
    container_name: viny-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./index.html:/app/index.html:ro
      - ./vite.config.js:/app/vite.config.js:ro
      - ./package.json:/app/package.json:ro
      - ./tailwind.config.js:/app/tailwind.config.js:ro
      - ./postcss.config.js:/app/postcss.config.js:ro
      # Mount node_modules as volume for performance
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3001/api
    command: npm run dev -- --host 0.0.0.0
    networks:
      - viny-network
    depends_on:
      backend:
        condition: service_healthy

volumes:
  # Persistent database storage
  viny_db:
    driver: local
  # Node modules volumes for better performance
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  viny-network:
    driver: bridge