blank_issues_enabled: false
contact_links:
  - name: Viny Discussions
    url: https://github.com/tomymaritano/viny/discussions
    about: Ask questions, share ideas, and discuss Viny with the community
  - name: Documentation
    url: https://github.com/tomymaritano/viny/tree/main/docs
    about: Read the documentation for setup, usage, and development guides
  - name: Roadmap
    url: https://github.com/tomymaritano/viny/blob/main/docs/ROADMAP.md
    about: View our development roadmap and planned features