name: Dev Checks

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '20'

jobs:
  quick-checks:
    name: Quick Development Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linter
        run: npm run lint
        continue-on-error: true
        
      - name: Check code formatting
        run: npm run format:check
        continue-on-error: true
        
      - name: Run quick tests
        run: npm run test:run
        
      - name: Build check
        run: npm run build
        
      - name: TypeScript check
        run: npm run build:electron-src

  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check for security vulnerabilities
        run: npm audit --audit-level=high
        continue-on-error: true
        
      - name: Check for outdated dependencies
        run: npm outdated
        continue-on-error: true