name: Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.1.2, v1.2.0, etc.

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build app
        run: npm run build
        
      - name: Build Electron app
        run: npm run build:electron
        env:
          # GitHub token for releases
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Code signing - will be enabled when secrets are added
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # Notarization
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # Enable notarization only if credentials are present
          NOTARIZE: ${{ secrets.APPLE_ID && 'true' || 'false' }}